### ISSUE TITLE
Retrieve Spotify Credentials from application.yml in code

### ISSUE THREAD

**Issue by jpfrehe** [SpotifyVotingQueue/svq-backend#1]
Need to auto wire the values from the credentials via value in the class SpotifyApiBuilder. 
Current method doesn't seem to work. 
Pls help :D

**Comment by CapOfCave** [comment]
1. Ich bin mir nicht sicher, ob @ Value an einem Companion Object funktioniert. Immerhin wird das doch als JVM-static compiliert, oder nicht?

2. Egal ob 1 jetzt geht oder (was ich glaube) nicht: mit `${abc.def}` verwendest du kotlins string interpolation, nicht die von Spring. Also das Dollar escapen:  `\${avc.de}`
