### ISSUE TITLE
Welchen Service für den Login Workflow aufrufen?

### ISSUE THREAD

**Issue by Sparkobbable** [SpotifyVotingQueue/svq-backend#5]
Aktuell verwende ich /user/me.
Welche Attribute erhalte ich zurück? Benutzername, Token?
Wie werde ich redirected zur Spotify Seite?

**Comment by CapOfCave** [comment]
Ich habe das Gefühl, das wir ganz falsch an die Sache rangehen. Implementier erstmal fleißig weiter Features, ich melde mich, wenn ich genaueres weiß

**Comment by CapOfCave** [comment]
Bis dahin ist die "richtige" login-URL aber `/oauth2/authorization/spotify`

**Comment by CapOfCave** [comment]
Nagut, scheint als wäre unser Weg doch größtenteils okay, wenn auch etwas merkwürdig. Sprich, die üblichen Optionen haben ihre eigenen Nachteile. Evtl. ändern wir es irgendwann nochmal, aber so sollte es eigentlich erstmal funktionieren.

Login per href an die o. g. URL (!! nicht im Hintergrund POST etc). Wir können die sicherlich bald auch noch auf /login ändern, ist aber jetzt bestimmt erstmal nicht so wichtig.

Ich bau den /user/me Endpoint dann zeitnah so um, dass er kein Login benötigt und ggf. sowas wie "nicht eingeloggter User" zurückgibt - natürlich dann in einem wunderschönen Format. Spontane Idee:
`{ authenticated: false }` bzw. `{ authenticated: true, displayName: "Mein Spotify-Name"}`
Auf Wunsch kann der Service noch die UserId zurückgeben, aber wenn die im Frontend eh nicht gebraucht wird, kann ich die auch weglassen
